# Generated by Django 4.2.5 on 2024-01-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evacore', '0002_remove_profile_email_profile_nivel_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
